### ISSUE TITLE
fails to open and folder

### ISSUE THREAD

**Issue by abiheiri** [netguy204/roku_media_server#12]
When trying actually play any video or music, it fails with this error

```
Traceback (most recent call last):
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/web/application.py", line 242, in process
    return self.handle()
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/web/application.py", line 387, in handle_class
    return tocall(*args)
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/mymedia.py", line 909, in GET
    return getdoc(feed.key, path, base_dir, range, config, collapse_collections).to_xml()
  File "/usr/home/al/netguy204-roku_media_server-932629b/server/mymedia.py", line 566, in getdoc
    for base, dirs, files in os.walk(path):
  File "/usr/local/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

**Comment by netguy204** [comment]
What operating system are you using? Regardless, can you try this version and let me know if it fixes the problem? https://github.com/Bandicoot/roku_media_server/archive/channel.zip

**Comment by abiheiri** [comment]
Thanks that worked. Also had to follow "roens" suggestion here: http://forums.roku.com/viewtopic.php?f=28&t=25955&sid=316238c34c967f691dae6918d2019cb3&start=1635

Which was to comment out 

```
#  ensure("music_dir", default_music_path)
#  ensure("video_dir", default_video_path)
#  ensure("photo_dir", default_photo_path)
```

from common.py

OS: FreeBSD 9.1-RELEASE #0 r243825

**Comment by netguy204** [comment]
I've merged bandicoot's patch and added a better version of the fix above for free bsd. Thanks for the report.
